### ISSUE TITLE
How to handle "NULL" strings?

### ISSUE THREAD

**Issue by K2ouMais** [ellgreen/laravel-loadfile#10]
Hello,

is there a way to handle columns that have NULL as a string?

After the import that column doesnt have the word NULL and it is empty.

Thank you for your great package.

**Comment by ellgreen** [comment]
Hi @K2ouMais, I have just written a test that uploads a CSV with 'null' and 'NULL' as strings but seems to be working ok in the tests:

## Data

```csv
John Doe,1980-01-01,null
Jane Doe,1975-06-30,NULL
```

https://github.com/ellgreen/laravel-loadfile/blob/issue-10/tests/data/people-with-null-strings.csv

## Test
https://github.com/ellgreen/laravel-loadfile/blob/579ec4e1841bee9fd94b78cb76270fa7e8ad521a/tests/Feature/LoadFileTest.php#L120-L136

I'm not sure what's happening there, maybe it's a difference in the MySQL versions we are using or a setting MySQL.

**Comment by K2ouMais** [comment]
Hi there,

I think the problem I am having might be a MySQL limitation.

Do your tests work if you have a csv like this?

```
"Doe, John",1980-01-01,null,"Yet, another test"
"Doe, Jane",1975-06-30,NULL,"Yet, another test... Part 2"
```

It seems the NULL string isnt getting importing when handling with fixed lenghts.
