### ISSUE TITLE
Can't get it to load more than 300 rows

### ISSUE THREAD

**Issue by ingageco** [ellgreen/laravel-loadfile#17]
Any idea what i might be doing wrong? I have followed the steps, enabled the flag in the db config as well as mysql, but it stops at 300 every time. The file has a total of ~98k records.

**Comment by ingageco** [comment]
Sorry - must have been a memory issue or something similar. Eventually got it to load them all.

**Comment by ellgreen** [comment]
All good, glad to hear you got it working!
